# Generated by Django 3.0.8 on 2020-11-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
    ]
