# Generated by Django 3.0.8 on 2020-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lop', '0003_auto_20201116_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assignedto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateclosed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateopened',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
