# Generated by Django 3.0.8 on 2020-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lop', '0008_member_weeklyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='weeklyemail',
            field=models.BooleanField(default=True),
        ),
    ]
